### ISSUE TITLE
get_contact_by_id_with_http_info returns `JSON::ParserError: 419: unexpected token at '{` if contact is deleted

### ISSUE THREAD

**Issue by sampatbadhe** [bombbomb/bombbomb-ruby-openapi#3]
```
irb(main):009:0> BombBomb::ContactsApi.new(`BOMBBOMB_CLIENT`).get_contact_by_id_with_http_info(`BOMBBOMB_CONTACT_ID`)
JSON::ParserError: 419: unexpected token at '{
    "id": `BOMBBOMB_CONTACT_ID`,
    "user_id": `BOMBBOMB_USER_ID`,
    "int_source": "****",
    "first_name": "*****",
    "last_name": "*****",
    "email": "****@****.****",
    "business_name": "*********",
    "position": "*********r",
    "comments": "<html><head><script type="text/javascript">window.NREUM||(NREUM={}),__nr_require=function(e,t,n){function r(n){if(!t[n]){var o=t[n]={exports:{}};e[n][0].call(o.exports,function(t){var o=e[n][1][t];return r(o||t)},o,o.exports)}return t[n].exports}if("function"==typeof __nr_require)return __nr_require;for(var o=0;o<n.length;o++)r(n[o]);return r}({1:[function(e,t,n){function r(){}function o(e,t,n){return function(){return i(e,[f.now()].concat(u(arguments)),t?null:this,n),t?void 0:this}}var i=e("handle"),a=e(2),u=e(3),c=e("ee").get("tracer"),f=e("loader"),s=NREUM;"undefined"==typeof window.newrelic&&(newrelic=s);var p=["setPageViewName","setCustomAttribute","setErrorHandler","finished","addToTrace","inlineHit","addRelease"],d="api-",l=d+"ixn-";a(p,function(e,t){s[t]=o(d+t,!0,"api")}),s.addPageAction=o(d+"addPageAction",!0),s.setCurrentRouteName=o(d+"routeName",!0),t.exports=newrelic,s.interaction=function(){return(new r).get()};va]'
        from /app/vendor/bundle/ruby/2.3.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
        from /app/vendor/bundle/ruby/2.3.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
        from /app/vendor/bundle/ruby/2.3.0/gems/bombbomb-2.0.25797/lib/bombbomb/api_client.rb:163:in `deserialize'
        from /app/config/initializers/json_api_client.rb:18:in `call_api'
        from /app/vendor/bundle/ruby/2.3.0/gems/bombbomb-2.0.25797/lib/bombbomb/api/contacts_api.rb:434:in `get_contact_by_id_with_http_info'
        from (irb):9
        from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
        from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
        from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
```

**Comment by karanvalecha** [comment]
The 'comments' attribute here received has invalid string value - How can this fit into a JSON 🤔
